dbConfig:
    dbConfigFile: testnet/plutus-pab-remote.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9081
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5

walletServerConfig:
  # tag: LocalWalletConfig
  tag: RemoteWalletConfig
  # walletSettings:
  #   baseUrl: http://192.168.1.103:8090

nodeServerConfig:
  pscSocketPath: testnet/node.sock
  pscBaseUrl: "192.168.1.103"
  pscKeptBlocks: 2160
  pscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode

chainIndexConfig:
  ciBaseUrl: http://192.168.1.103:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

# metadataServerConfig:
#   mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: 1
  pabResumeFrom:
    # "tag" : "PointAtGenesis" }
      { "tag" : "Point"
      , "pointBlockId" : "d9bbed4cf8fb53d4853340a3bb5f60510d5be05ba1f57e3a814ac918b181a10f"
      , "pointSlot" : {"getSlot" : 55155507}
      }
