dbConfig:
    dbConfigFile: testnet/plutus-pab.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9081
  staticDir: plutus-pab-client/dist
  permissiveCorsPolicy: False
  # Optional timeout (in seconds) for calls to endpoints that are not currently
  # available. If this is not set, calls to unavailable endpoints fail
  # immediately.
  endpointTimeout: 5

walletServerConfig:
  tag: RemoteWalletConfig

nodeServerConfig:
  pscSocketPath: /home/chryd/Programming/crypto/plutus-apps/plutus-pab/test-node/testnet/node.sock
  pscBaseUrl: "localhost"
  pscKeptBlocks: 2160
  pscNetworkId: "1097911063" # Testnet network ID (main net = empty string)
  pscSlotConfig:
    scSlotZeroTime: 1596059091000 # Wednesday, July 29, 2020 21:44:51 - shelley launch time in milliseconds
    scSlotLength: 1000 # In milliseconds
  pscFeeConfig:
    fcConstantFee:
      getLovelace: 10 # Constant fee per transaction in lovelace
    fcScriptsFeeFactor: 1.0 # Factor by which to multiply size-dependent scripts fee in lovelace
  pscInitialTxWallets: []
  pscNodeMode: AlonzoNode

chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses: []

requestProcessingConfig:
  requestProcessingInterval: 1

# TODO: Found this in plutus-apps, should I use?
# signingProcessConfig:
#   spBaseUrl: http://localhost:9084
#   spWallet:
#     getWallet: 1

# metadataServerConfig:
#   mdBaseUrl: http://localhost:9085

developmentOptions:
  pabRollbackHistory: null
  pabResumeFrom:
    # "tag" : "PointAtGenesis" }
      { "tag" : "Point"
      , "pointBlockId" : "a8756c78e3ee655fcbf07db340c5b451679a6712eac3a0bc7cebed2da99e01ae"
      , "pointSlot" : {"getSlot" : 56266383}
      }

